INSERT INTO `book` (`id`, `publisher`, `genre`, `image_path`, `title`, `authorName`, `description`, `price`) VALUES
(1, 'Bantam Spectra', 'Fantasy', 'https://github.com/GustavoPT/GeekTextImages/blob/master/cover_gameofthrones01.jpg?raw=true', 'A Game of Thrones', 'George R. R. Martin', 'A Game of Thrones is the first novel in A Song of Ice and Fire, a series of fantasy novels', '19.99'),
(2, 'Bloomsbury', 'Fantasy', 'https://github.com/GustavoPT/GeekTextImages/blob/master/HP_SS.jpg?raw=true','Harry Potter and the Sorcerer''s Stone', 'J. K. Rowling', 'Harry finds himself drawn deep inside a mystical world he never knew existed and closer to his own noble destiny.','9.99'),
(3, 'Chatto & Windus', 'Science Fiction', 'https://github.com/GustavoPT/GeekTextImages/blob/master/BNW.jpg?raw=true','Brave New World', 'Aldous Huxley', 'masterpiece ... one of the most prophetic dystopian works of the 20th century.','14.99'),
(4, 'Allen & Unwin', 'Fantasy', 'https://github.com/GustavoPT/GeekTextImages/blob/master/TFotR.jpg?raw=true','The Fellowship of the Ring', 'J. R. R. Tolkien', 'The first volume in J.R.R. Tolkien''s epic adventure THE LORD OF THE RINGS', '11.99'),
(5, 'Simon & Schuster', 'Mystery', 'https://github.com/GustavoPT/GeekTextImages/blob/master/EAP.jpg?raw=true','Edgar Allan Poe: Complete Tales and Poems', 'Edgar Allan Poe', 'His complete early and miscellaneous poetic masterpieces.', '10.99');

INSERT INTO `authors` (`AuthorID`, `AuthorName`, `AuthorBio`) VALUES
(1, 'George R. R. Martin', 'Born in 1948, fantasy writer George R. R. Martin grew up in Bayonne, New Jersey. He developed a love for writing early on. His first novel, Dying of the Light, debuted in 1977. In 1996, he published his first installment of the A Song of Ice and Fire series. Martin became a best-selling author in 2005 with the fourth title A Feast for Crows and again in 2011 with the fifth A Dance with Dragons.'),
(2, 'J. K. Rowling', 'Joanne Rowling, writing under the pen names J. K. Rowling and Robert Galbraith, is a British novelist, philanthropist, film and television producer and screenwriter best known for writing the Harry Potter fantasy series.'),
(3, 'Aldous Huxley', 'Aldous Leonard Huxley was an English writer, novelist, philosopher, and prominent member of the Huxley family. He graduated from Balliol College at the University of Oxford with a first-class honours degree in English literature. The author of nearly fifty books, Huxley was best known for his novels (among them Brave New World, set in a dystopian future); for nonfiction works, such as The Doors of Perception, in which he recalls his experiences taking psychedelic drugs; and for his wide-ranging essays. Early in his career, Huxley published short stories and poetry, and edited the literary magazine Oxford Poetry. He went on to publish travel writing, film stories, satire, and screenplays. He spent the latter part of his life in the United States, living in Los Angeles from 1937 until his death.'),
(4, 'J. R. R. Tolkien', 'John Ronald Reuel Tolkien was an English writer, poet, philologist, and university professor who is best known as the author of the classic high fantasy works The Hobbit, The Lord of the Rings, and The Silmarillion.'),
(5, 'Edgar Allen Poe', 'Edgar Allan Poe was an American writer, editor, and literary critic. Poe is best known for his poetry and short stories, particularly his tales of mystery and the macabre. He is widely regarded as a central figure of Romanticism in the United States and American literature as a whole, and he was one of the country earliest practitioners of the short story. Poe is generally considered the inventor of the detective fiction genre and is further credited with contributing to the emerging genre of science fiction. He was the first well-known American writer to try to earn a living through writing alone, resulting in a financially difficult life and career.');